baseurl:

# Development optimizations for frontpage-only work
limit_posts: 30

# Just on plugin
plugins:
  - jekyll-paginate

# Exclude old content to speed up builds
exclude:
  - crawl
  - crawl_sites
  - script
  - vendor
  - tmp
  - _posts/2015
  - _posts/2016
  - _posts/2017
  - _posts/2018
  - _posts/2019
  - _posts/2020
  - _posts/2021
  - _posts/2022
  - _posts/2023
  - _posts/2024
  - _posts/2025
