# Permalinks
#
permalink:           /:year/:month-:day.html

# Setup
title:               Ráfagas
tagline:             Geospatial links everyday
site.github.url:     https://geoinquiets.github.io
url:                 https://geoinquiets.github.io
baseurl:             /rafagas

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Rafagas
  url:               https://en.osm.town/@rafagaslinks
  email:             xurxosanz@gmail.com


# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/geoinquiets/rafagas

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - "_pages"

exclude:
  - ".git"
  - "README.md"
  - "LICENSE.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "Rakefile"
  - "vendor"
  - "script"
  - "crawl"
  - "crawl_sites"
  - "tmp"
  - "env"
  - "docker-compose.yml"
  - "Makefile"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author: Raf
      twitter: LinksGeo

highlighter: null

theme: minima
minima:
  date_format: "%Y-%m-%d"
repository: geoinquiets/rafagas